version: "3"

services:
  cnode:
    image: cardanocommunity/cardano-node:latest
    container_name: cnode
    # environment: 
    #   NETWORK: testnet
    env_file: .env
    security_opt:
      - no-new-privileges:false
    volumes: 
      - ./priv:/opt/cardano/cnode/priv
      - ./.env:/home/guild/.env
      - ./scripts:/home/guild/scripts
      - ./samples/config:/home/guild/.ssh/config
    entrypoint: bash
